### ISSUE TITLE
2.3.2 is broken

### ISSUE THREAD

**Issue by nebulous42069** [jmooremcc/Repository.jmooremcc#11]
2.3.2 update came through today, and now SF just throws an error: 
2023-08-08 14:56:01.440 T:37292   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'OSError'>
                                                   Error Contents: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'special://profile/addon_data/plugin.program.super.favourites/ImageCache'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\xxxx\AppData\Roaming\Kodi\addons\plugin.program.super.favourites\default.py", line 198, in <module>
                                                       checkImageCacheStatus()
                                                     File "C:\Users\xxxx\AppData\Roaming\Kodi\addons\plugin.program.super.favourites\imagecache.py", line 120, in checkImageCacheStatus
                                                       os.mkdir(IMAGECACHE)
                                                   OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'special://profile/addon_data/plugin.program.super.favourites/ImageCache'
                                                   -->End of Python script error report<--

**Comment by nebulous42069** [comment]
This is Kodi Nexus 20.2 btw.

**Comment by jmooremcc** [comment]
Go into settings and verify the location of your SF folder, then run it.

**Comment by nebulous42069** [comment]
> Go into settings and verify the location of your SF folder, then run it.
Yes, I know that works, however it doesnt work on a fresh install of the addon. Its blank. It also does not work with my pervious settings after it updated which was special://home/userdata/addon_data/plugin.program.superfavourites. I would think the special......addon_data should be the default location hardcoded, unless you wanted to change it for some reason.

**Comment by nebulous42069** [comment]
> Go into settings and verify the location of your SF folder, then run it.

Yes, I know that works, however it doesnt work on a fresh install of the addon. Its blank. It also does not work with my pervious settings after it updated which was special://home/userdata/addon_data/plugin.program.superfavourites. I would think the special......addon_data should be the default location hardcoded, unless you wanted to change it for some reason.

**Comment by jmooremcc** [comment]
> > Go into settings and verify the location of your SF folder, then run it.
> 
> Yes, I know that works, however it doesnt work on a fresh install of the addon. Its blank. It also does not work with my pervious settings after it updated which was special://home/userdata/addon_data/plugin.program.superfavourites. I would think the special......addon_data should be the default location hardcoded, unless you wanted to change it for some reason.

According to the code, the default SF folder location should be in the userdata in the addon's data, so the error you reported should not be happening.  I'll investigate more to see what's going on.

**Comment by BMcGraw51** [comment]
I concur. v2.3.2 gives me the same errors in the kodi log. I thought I had found "relief" by reinstalling the old 2.0.10 version but...
I doesn't crash at least but it no longer works. The folders appear as normal but none of the "links" work.

**Comment by BMcGraw51** [comment]
FYI Your suggestion: "Go into settings and verify the location of your SF folder, then run it." doesn't help either. Mine already shows the correct folder location.

**Comment by BMcGraw51** [comment]
![Screenshot 2023-08-09 08 53 14](https://github.com/jmooremcc/Repository.jmooremcc/assets/97324632/309866de-9d05-48d1-8366-f8cf89c66c29)
![Screenshot 2023-08-09 08 50 03](https://github.com/jmooremcc/Repository.jmooremcc/assets/97324632/9c975646-135f-4e9d-a0bb-b089b28d5f9e)

**Comment by BMcGraw51** [comment]
Thought these screenshots might help. BTW, Kodi 20.2. Same thing happens in Android OS and Windows 10.

**Comment by BMcGraw51** [comment]
Adding the correct location on an Android 11/12 TV box isn't doable. One can no longer access the Android/.kodi/ data folder due to new restrictions.  No way to delete the sf folder for a "fresh" install either.

**Comment by BMcGraw51** [comment]
Rolling back to v2.2.5 seems to be an acceptable alternative (until 2.3.2 is patched anyway)
