### ISSUE TITLE
SF v2.3.5 not working, v2.3.4 works fine

### ISSUE THREAD

**Issue by cg00001** [jmooremcc/Repository.jmooremcc#13]
![1](https://github.com/jmooremcc/Repository.jmooremcc/assets/38960370/469725ec-ce9b-4e4e-877d-43531dc9fc4a)
This is in Arch Linux in Kodi Omega, but a friend with android & Kodi Nexus has the same issue.
SF produces the error and doesn't show the Super Favourites.

**Comment by vnnegt** [comment]
same issue here on nvidia shield running kodi `20.2`

**Comment by odelot80** [comment]
Hi!, I hace the same problem in Kodi 19.4 in Windows 10, I copy/paste the log error:

ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <class 'OSError'>
Error Contents: [WinError 123] El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos: 'special://profile/addon_data/plugin.program.super.favourites/ImageCache'
Traceback (most recent call last):
File "C:\Users\PC_Dell\AppData\Roaming\Kodi\addons\plugin.program.super.favourites\default.py", line 199, in <module>
checkImageCacheStatus()
File "C:\Users\PC_Dell\AppData\Roaming\Kodi\addons\plugin.program.super.favourites\imagecache.py", line 127, in checkImageCacheStatus
os.mkdir(IMAGECACHE)
OSError: [WinError 123] El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos: 'special://profile/addon_data/plugin.program.super.favourites/ImageCache'
-->End of Python script error report<--

**Comment by jmooremcc** [comment]
I've fixed the issue in SF 2.3.6

**Comment by odelot80** [comment]
Hi again!, updated to version 2.3.6... Now running without problems.

Many thanks and regards!! ;)
