### ISSUE TITLE
Super favourites hebrew chars support (latin1 encoding issue)

### ISSUE THREAD

**Issue by tstrul1** [jmooremcc/Repository.jmooremcc#2]
Hey,
Hebrew characters looks like gibberish since kodi19.

tried to look it up and it looks like latin1 encoding which is used here has doesnt work with hebrew. utf-8 works though.

Any chance to fix this?

Thank you!

**Comment by jmooremcc** [comment]
Which version of Kodi Matrix are you running?
SF 2.0.7 worked with Kodi 19.0 but didn't work well with version 19.1. 
That's why SF 2.0.9 came into existence.
If you could provide a log, that would be helpful.

**Comment by tstrul1** [comment]
Hey,
Im using SF 2.0.9 on kodi 19.1 (windows 10)
not sure if there is anything interested in logs  because its a display thing... hebrew chars looks like this
![image](https://user-images.githubusercontent.com/13537257/120935370-1ffa5800-c70b-11eb-980c-b5946acb9e11.png)

but they are clickable and working
its not a skin issue skin is using arial based font that support hebrew and RTL chars - only happens in SF.
when i tried replacing latin1 encoding with utf-8 locally - it worked

**Comment by Tstrul-work** [comment]
This is a log where i enter SF and the desired addon in Hebrew.
everything works except display :
https://pastebin.com/raw/wKnTAmjg

**Comment by tstrul1** [comment]
This is a log where i enter SF and the desired addon in Hebrew.
everything works except display :
https://pastebin.com/raw/wKnTAmjg

**Comment by jmooremcc** [comment]
I'm close to releasing a fix which will resolve your issue.

**Comment by Tstrul-work** [comment]
Thank you very much
addon updated and Hebrew works great

**Comment by tstrul1** [comment]
Thanks,
just updated the addon and the fix works great
