### ISSUE TITLE
Can't download

### ISSUE THREAD

**Issue by EvilOneIsMe** [jmooremcc/Repository.jmooremcc#4]
Download doesn't seem to work?

**Comment by jmooremcc** [comment]
I need a bit more information to understand the problem.

**Comment by EvilOneIsMe** [comment]
> I need a bit more information to understand the problem.

Ok when you use SF if you right click on a movie your watching it should popup a box, and one of the options is to download it with SF. It doesn't do that. The version I used with Kodi 18.9 worked great. I could use RD to download and get the movie to download..

**Comment by jmooremcc** [comment]
I've just release SF Version 2.11 which should fix this problem.
There are some sites that don't allow the copy operation and I can't do anything about that.
However, the sites I tested that do allow the copy operation, SF worked fine.

**Comment by EvilOneIsMe** [comment]
Took me awhile to figure out how to download it. I'll try and explain it. The 18.9 ver you can just right click it the playing movie and it would let you download it. This new button doesn't do anything. After many attempts, after the movie is playing I can hit the esc key and go back the the link I started the movie from hit the right key and it brings up the SF menu with DOWNLOAD at the bottom and it works. Seems sort of a roundabout way of doing it, unless I'm doing it wrong (Grin)??? Thanks for your help and the work your doing on SF, its a great program..

**Comment by EvilOneIsMe** [comment]
Ok I've downloaded a few movies and its working OK the way it is. Just don't know how many users are going to figure out it works different. Its simple after you figure out you have to go back to the link you started the movie from. Thanks!!

**Comment by jmooremcc** [comment]
You're welcome and thanks to avid SF users like yourself, I'm learning more and more about the features the original developer put into the addon. It's a great addon with many features that Kodi doesn't have.
